import sys;sys.path.append('/u/nrahman/workspace/nada/branches/pynada/')
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import h5py
from plotter import plotter;tp=plotter();hp=plotter()
from analysis import analysis;ta=analysis();ha=analysis()
mpl.rcParams['axes.grid'] = True
model='c115';dir='/ptmp/nrahman/collapse/'+model+'/data3D/'
hp.read(dir);ha.read(dir);hp.touch();ha.touch()
tp.read(dir+'neutrinos');ta.read(dir+'neutrinos');tp.touch();ta.touch()

t_b = ha.gettime(26,26)
time_tr=ta.timesteps
time_hy=ha.timesteps

vr=ha.readvar('velocity/velx',time_hy-110,time_hy)[:,0,:,:].T
s=ha.readvar('s',time_hy-110,time_hy)[:,0,:,:].T
vt=ha.readvar('velocity/vely',time_hy-110,time_hy)[:,0,:,:].T*ha.x[:,None,None]
ye=ha.readvar('ye',time_hy-110,time_hy)[:,0,:,:].T
se=(ta.readvar('SE',time_tr-110,time_tr)/ta.readvar('rho',time_tr-110,time_tr))[:,0,0,:,:].T

xlimit=[0,400];ylimit=[-400,400]
x=ha.x[:,None]*np.cos(ha.y[None,:])/1e5
y=ha.x[:,None]*np.sin(ha.y[None,:])/1e5

var=vr;mpl.rcParams['image.cmap'] = 'seismic';lrange=np.linspace(-0.1,+0.1,201)
fvr=plt.figure(1)
fvr.add_subplot(2,6,1);plt.contourf(y.T,x.T,var[:,:,-110].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,2);plt.contourf(y.T,x.T,var[:,:,-100].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,3);plt.contourf(y.T,x.T,var[:,:,-90].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,4);plt.contourf(y.T,x.T,var[:,:,-80].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,5);plt.contourf(y.T,x.T,var[:,:,-70].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,6);plt.contourf(y.T,x.T,var[:,:,-60].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
fvr.add_subplot(2,6,7);plt.contourf(y.T,x.T,var[:,:,-50].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,8);plt.contourf(y.T,x.T,var[:,:,-40].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,9);plt.contourf(y.T,x.T,var[:,:,-30].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,10);plt.contourf(y.T,x.T,var[:,:,-20].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,11);plt.contourf(y.T,x.T,var[:,:,-10].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvr.add_subplot(2,6,12);plt.contourf(y.T,x.T,var[:,:,-1].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
plt.suptitle(model+' tpb='+str(ha.time-t_b).replace('[','').replace(']','')+'s'+' vr [c]')

var=vt;mpl.rcParams['image.cmap'] = 'seismic';lrange=np.linspace(-0.1,+0.1,201)
fvt=plt.figure(2)
fvt.add_subplot(2,6,1);plt.contourf(y.T,x.T,var[:,:,-110].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,2);plt.contourf(y.T,x.T,var[:,:,-100].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,3);plt.contourf(y.T,x.T,var[:,:,-90].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,4);plt.contourf(y.T,x.T,var[:,:,-80].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,5);plt.contourf(y.T,x.T,var[:,:,-70].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,6);plt.contourf(y.T,x.T,var[:,:,-60].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
fvt.add_subplot(2,6,7);plt.contourf(y.T,x.T,var[:,:,-50].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,8);plt.contourf(y.T,x.T,var[:,:,-40].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,9);plt.contourf(y.T,x.T,var[:,:,-30].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,10);plt.contourf(y.T,x.T,var[:,:,-20].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,11);plt.contourf(y.T,x.T,var[:,:,-10].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fvt.add_subplot(2,6,12);plt.contourf(y.T,x.T,var[:,:,-1].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
plt.suptitle(model+' tpb='+str(ha.time-t_b).replace('[','').replace(']','')+'s'+' vt [c]')

var=s;var[var<10]=10;var[var>20]=20;mpl.rcParams['image.cmap'] = 'jet';lrange=np.linspace(10,20,201)
fs=plt.figure(3)
fs.add_subplot(2,6,1);plt.contourf(y.T,x.T,var[:,:,-110].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,2);plt.contourf(y.T,x.T,var[:,:,-100].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,3);plt.contourf(y.T,x.T,var[:,:,-90].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,4);plt.contourf(y.T,x.T,var[:,:,-80].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,5);plt.contourf(y.T,x.T,var[:,:,-70].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,6);plt.contourf(y.T,x.T,var[:,:,-60].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
fs.add_subplot(2,6,7);plt.contourf(y.T,x.T,var[:,:,-50].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,8);plt.contourf(y.T,x.T,var[:,:,-40].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,9);plt.contourf(y.T,x.T,var[:,:,-30].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,10);plt.contourf(y.T,x.T,var[:,:,-20].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,11);plt.contourf(y.T,x.T,var[:,:,-10].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fs.add_subplot(2,6,12);plt.contourf(y.T,x.T,var[:,:,-1].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
plt.suptitle(model+' tpb='+str(ha.time-t_b).replace('[','').replace(']','')+'s'+' s [kb/baryon]')

var=se;var[var<-1e21]=-1e21;var[var>1e21]=1e21;mpl.rcParams['image.cmap'] = 'jet';lrange=np.linspace(-1.01e21,1.01e21,201) 
fse=plt.figure(4)
fse.add_subplot(2,6,1);plt.contourf(y.T,x.T,var[:,:,-110].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,2);plt.contourf(y.T,x.T,var[:,:,-100].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,3);plt.contourf(y.T,x.T,var[:,:,-90].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,4);plt.contourf(y.T,x.T,var[:,:,-80].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,5);plt.contourf(y.T,x.T,var[:,:,-70].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,6);plt.contourf(y.T,x.T,var[:,:,-60].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
fse.add_subplot(2,6,7);plt.contourf(y.T,x.T,var[:,:,-50].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,8);plt.contourf(y.T,x.T,var[:,:,-40].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,9);plt.contourf(y.T,x.T,var[:,:,-30].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,10);plt.contourf(y.T,x.T,var[:,:,-20].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,11);plt.contourf(y.T,x.T,var[:,:,-10].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fse.add_subplot(2,6,12);plt.contourf(y.T,x.T,var[:,:,-1].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
plt.suptitle(model+' tpb='+str(ha.time-t_b).replace('[','').replace(']','')+'s'+' se [erg/gm/s]')

var=ye;mpl.rcParams['image.cmap'] = 'seismic';lrange=np.linspace(0.12,0.2,201);xlimit=[0,30];ylimit=[-30,30]
fye=plt.figure(5)
fye.add_subplot(2,6,1);plt.contourf(y.T,x.T,var[:,:,-110].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,2);plt.contourf(y.T,x.T,var[:,:,-100].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,3);plt.contourf(y.T,x.T,var[:,:,-90].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,4);plt.contourf(y.T,x.T,var[:,:,-80].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,5);plt.contourf(y.T,x.T,var[:,:,-70].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,6);plt.contourf(y.T,x.T,var[:,:,-60].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
fye.add_subplot(2,6,7);plt.contourf(y.T,x.T,var[:,:,-50].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,8);plt.contourf(y.T,x.T,var[:,:,-40].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,9);plt.contourf(y.T,x.T,var[:,:,-30].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,10);plt.contourf(y.T,x.T,var[:,:,-20].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,11);plt.contourf(y.T,x.T,var[:,:,-10].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.gca().set_aspect(1)
fye.add_subplot(2,6,12);plt.contourf(y.T,x.T,var[:,:,-1].T,levels=lrange)
plt.xlim(xlimit);plt.ylim(ylimit);plt.xlabel('y [km]');plt.ylabel('x [km]');plt.colorbar();plt.gca().set_aspect(1)
plt.suptitle(model+' tpb='+str(ha.time-t_b).replace('[','').replace(']','')+'s'+' ye')

plt.show()

